{"name": "test_LongParam", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <test_plugins.Test_plugins object at 0x0000021881EDCF70>\n\n    def test_LongParam(self):\n        name1 = \"LongParam\"\n        self.p2 = modify_conf_file()\n        self.p2.SetPluginParams()\n        self.p1.send_cmd(\"tftp -g -r testserver.conf 192.168.1.65\")\n        rel = self.p1.send_cmd(\"ls -l\")\n        self.p1.log(rel,name1,self.nowtime)\n        rel=self.p1.send_cmd(\"kill -USR1 `pidof testserver`\")\n        rel=self.p1.send_enter()\n        self.p1.log(rel,name1,self.nowtime)\n        rel = re.findall(r'\"Status\":\"(\\S)\"',rel)\n        print(rel)\n        print(type(rel))\n>       if rel[0] == \"0\":\nE       IndexError: list index out of range\n\ntest_plugins.py:35: IndexError"}, "attachments": [{"name": "log", "source": "85487fa9-32d2-481f-a861-164f6e2b81a0-attachment.txt", "type": "text/plain"}], "start": 1700727262181, "stop": 1700727262355, "uuid": "c563601e-0101-4e03-bd0e-b27845eeab26", "historyId": "ada529718f23cb5a4760f3e163b5afbe", "testCaseId": "ada529718f23cb5a4760f3e163b5afbe", "fullName": "test_plugins.Test_plugins#test_LongParam", "labels": [{"name": "suite", "value": "test_plugins"}, {"name": "subSuite", "value": "Test_plugins"}, {"name": "host", "value": "l29707B"}, {"name": "thread", "value": "10648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_plugins"}]}